import Head from 'next/head'
import AnimatedText from '@/components/common/AnimatedText'
import DefaultButton from '@/components/common/button/DefaultButton'

export default function Home() {
  return (
    <> 
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center justify-between w-full'>
        <div className='w-1/2'>

        </div>
        <div className='w-1/2 flex flex-col items-center self-center'>
          <h1>Turning Vision Into Reality With Code.</h1>
          <AnimatedText text="Turning Vision Into Reality With Code." className='!text-6xl !text-left' />
          <p className='my-4 text-base font-medium'>
          As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
          </p>
          <div className='flex items-center self-start mt-2'>
            <DefaultButton link="/dummy.pdf" title="Resume" download={true} />
            <DefaultButton link="mailto:hassanpumped17@gmail.com" title="Contact" download={false} />
          </div>
        </div>
      </main>
    </>
    
  )
}
