import Head from 'next/head'
import AnimatedText from '@/components/common/AnimatedText'
import DefaultButton from '@/components/common/button/DefaultButton'
import { sortRecentRepo } from '@/library/RecentCommit'
import { ReactNode, useEffect, useState } from 'react'
import NewSpeed from '@/components/newsFeed/NewsFeed'

export type commitType = {
  name: string;
  id: number;
  updated_at: string;
}

export default function Home() {

  const callFetchRecentCommit = async () => {
    return setCommits(await sortRecentRepo(10));
  }

  const [commits, setCommits] = useState<commitType[] | undefined>([]);
  useEffect(() => {
    callFetchRecentCommit();
  }, [])
  return (
    <> 
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center justify-between w-full'>
        <div className='w-1/2 flex flex-col items-center self-center'>
          <h1>Turning Vision Into Reality With Code.</h1>
          <AnimatedText text="Turning Vision Into Reality With Code." className='!text-6xl !text-left' />
          <p className='my-4 text-base font-medium'>
          As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
          </p>
          <div className='flex items-center self-start mt-2'>
            <DefaultButton link="/dummy.pdf" title="Resume" download={true} />
            <DefaultButton link="mailto:hassanpumped17@gmail.com" title="Contact" download={false} />
          </div>
        </div>
        <div className='w-1/2 border border-dark bg-slate-100'>
          <h2 className='w-full text-center font-bold text-2xl'>Recent Commited Ropository</h2>
          <div className='w-full flex flex-wrap'>
            {
            commits?.map(({name, id, updated_at}: commitType) => {
              return (
                <div key={id} className='w-1/2'>
                  <NewSpeed id={id} updated_at={updated_at} name={name} />
                </div>   
              )
            })
          }
          </div>
        </div>
      </main>
    </>
    
  )
}
