import Head from 'next/head'
import AnimatedText from '@/components/common/AnimatedText'
import DefaultButton from '@/components/common/button/DefaultButton'
import { sortRecentRepo } from '@/library/RecentCommit'
import { useEffect, useRef, useState } from 'react'
import NewSpeed from '@/components/common/NewsFeed'
import ScrollToTopButton from '@/components/common/button/ScrollToTopButton'

export type commitType = {
  name: string;
  id: number;
  pushed_at: string;
}

export default function Home() {
  const [commits, setCommits] = useState<commitType[] | undefined>([]);
  const scrollRef = useRef<HTMLDivElement>(null);
  const callFetchRecentCommit = async (count: number) => {
    return setCommits(await sortRecentRepo(count));
  }

  useEffect(() => {
    callFetchRecentCommit(5);
  }, [])
  return (
    <> 
      <Head>
        <title>Resister-boy | Home</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='flex items-center justify-between w-full h-screen fixed bg-light'>
        <div className='w-1/2 bg-slate-200 relative mx-32 mt-4 rounded-2xl pt-4 mb-12 bg-gradient-to-b from-slate-200 to-light shadow-2xl overflow-hidden'>
          <div className='w-full h-[500px] flex justify-center items-center flex-wrap overflow-auto scroll-smooth pt-2 pb-12' ref={scrollRef}>
          {
            commits?.map(({name, id, pushed_at}: commitType) => {
              return (
                <div key={id} className='w-4/5 mb-4 mx-auto flex justify-center items-center'>
                  <NewSpeed id={id} pushed_at={pushed_at} name={name} />
                </div>   
              )
            })
          }
          </div>
          <div className='w-full py-4 flex justify-center items-center text-[#878787] duration-150 absolute bottom-0 backdrop-blur-lg'>
            <button onClick={(() => {
                callFetchRecentCommit(commits && commits.length <= 30 ? commits?.length + 3 : 3);
                if (scrollRef.current !== null && commits && commits?.length <= 30) {
                  scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
                }
            })} className='flex justify-center relative hover:underline'>
              see more
            </button>
            <ScrollToTopButton domRef={scrollRef} top='-top-8' right='right-8' />
          </div>
        </div>
        <div className='w-1/2 flex flex-col items-center self-center'>
          <h1>Turning Vision Into Reality With Code.</h1>
          <AnimatedText text="Turning Vision Into Reality With Code." className='!text-6xl !text-left' />
          <p className='my-4 text-base font-medium text-start'>
          As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
Explore my latest projects and articles, showcasing my expertise in React.js and web development.
          </p>
          <div className='flex items-center self-start mt-2'>
            <DefaultButton link="/dummy.pdf" title="Resume" icon={true} className='p-2.5 px-6 bg-dark' assets={null} />
            <DefaultButton link="mailto:hassanpumped17@gmail.com" title="Contact" icon={false} className='p-2.5 px-6 bg-dark' assets={null} />
          </div>
        </div>
      </main>
    </>
    
  )
}
