import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import AnimatedText from '@/components/common/AnimatedText'
import { NextPage } from 'next'
import { ProjectFeed } from '@/components/common/ProjectFeed'
import { IProject } from '@/interface/IProjectsFeed'
import { parseProject } from '@/library/ParseProject'
import ProjectSmallFeed from '@/components/common/ProjectSmallFeed'

const Projects:NextPage<any> = ({ projects }) => {
  const projectList: IProject[] = parseProject(projects);
  return (
    <>
      <Head>
        <title>Resister-boy | Projects</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='w-full mb-16 flex flex-col items-center'>
        <div className='pt-16'>
          <AnimatedText text="Imagination Trumps Knowledge!" className='text-6xl mt-12 text-[#333]'/>
          <div className='w-2/3 mt-8 mx-auto flex flex-wrap justify-between'>
            {projectList.map((project: IProject, index: number) => {
              return (
                project.idx % 3 === 1 ?
                (
                <ProjectFeed
                  key={index}
                  project={project}
                />
                ) : (
                  <div className={`w-1/2 ${project.idx % 2 === 0 ? 'pr-5' : 'pl-5'}`} key={index}>
                    <ProjectSmallFeed 
                      project={project}
                    />
                  </div>
                ))})}
          </div>
        </div>
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const options = {
    method: 'POST',
    headers: {
      Accept: 'application/json', 
      'Notion-Version': '2022-02-22',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${process.env.PROJECT_PASSWORD}`
    },
    body: JSON.stringify({
      sorts: [
          {
              "property": "Name",
              "direction": "ascending"
          }
      ],
      page_size: 100
    })
  };
  const response = await fetch(`https://api.notion.com/v1/databases/${process.env.PROJECT_APIKEY}/query`, options)
  const projects = await response.json()
  return {
    props: {
      projects
    }
  }
}


export default Projects