import React from 'react'
import Head from 'next/head'
import AnimatedText from '@/components/common/AnimatedText'

const projects = () => {
  return (
    <>
      <Head>
        <title>Resister-boy | Projects</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main className='w-full mb-16 flex flex-col items-center'>
        <div className='pt-16'>
          <AnimatedText text="Imagination Trumps Knowledge!" />
          <div className='grid grid-cols-12 gap-24'>
            <div className='col-span-12'>
              Featured Projects
            </div>
            <div className='col-span-6'>
              Prject-1
            </div>
            <div className='col-span-6'>
              Prject-2
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export default projects